# Generated by Django 5.1.6 on 2025-02-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(help_text='Name of the employee', max_length=200)),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=40)),
                ('Father_Name', models.CharField(max_length=200)),
                ('Marital_Status', models.CharField(blank=True, choices=[('Un Married', 'Un Married'), ('Married', 'Married')], default='Un Married', max_length=40, null=True)),
                ('Current_Address', models.TextField()),
                ('Permanent_Address', models.TextField()),
                ('Contact_Number', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Addhar_number', models.CharField(max_length=15)),
                ('Pan_number', models.CharField(max_length=15)),
                ('Emergency_Contact_Number', models.CharField(max_length=30)),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
