# Generated by Django 5.1.6 on 2025-03-01 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(help_text='Name of the employee', max_length=200, verbose_name='Full name')),
                ('Date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=40, verbose_name='Gender')),
                ('Father_Name', models.CharField(max_length=200, verbose_name='Fathers Name')),
                ('Marital_Status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Un Married', 'Un Married')], default='Un Married', max_length=40, null=True, verbose_name='Maritial Status')),
                ('Current_Address', models.TextField(verbose_name='Current Address')),
                ('Permanent_Address', models.TextField(verbose_name='Permanent Address')),
                ('Contact_Number', models.CharField(max_length=30, verbose_name='Contact Details')),
                ('Email_id', models.EmailField(max_length=254)),
                ('Addhar_number', models.CharField(max_length=15)),
                ('Pan_number', models.CharField(max_length=15)),
                ('Emergency_Contact_Number', models.CharField(max_length=30)),
                ('Job_role', models.TextField(blank=True, default='')),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_method', models.CharField(max_length=500)),
                ('Payment_date', models.DateField()),
                ('Designatory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gross_Salary', models.CharField(max_length=50, verbose_name='Gross Salary (Total Earnings)')),
                ('Total_decuctions', models.CharField(max_length=50, verbose_name='Total Deductions')),
                ('Net_Salary', models.CharField(max_length=50, verbose_name='Net Salary (Take-Home Pay)')),
                ('Created_at', models.DateTimeField(auto_now=True)),
                ('Designatory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee_management.employee', verbose_name='Employee')),
            ],
        ),
    ]
