# Generated by Django 5.1.6 on 2025-02-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0002_employee_job_role_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='Net_Salary',
            field=models.CharField(default=1, max_length=50, verbose_name='Net Salary (Take-Home Pay)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=40),
        ),
    ]
