# Generated by Django 5.1.6 on 2025-02-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0003_salary_created_at_salary_net_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Contact_Number',
            field=models.CharField(max_length=30, verbose_name='Contact Details'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Current_Address',
            field=models.TextField(verbose_name='Current Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Father_Name',
            field=models.CharField(max_length=200, verbose_name='Fathers Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Full_Name',
            field=models.CharField(help_text='Name of the employee', max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=40, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('Un Married', 'Un Married'), ('Married', 'Married')], default='Un Married', max_length=40, null=True, verbose_name='Maritial Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Permanent_Address',
            field=models.TextField(verbose_name='Permanent Address'),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_method', models.CharField(max_length=500)),
                ('Payment_date', models.DateField()),
                ('Designatory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employee_management.employee')),
            ],
        ),
    ]
