# Generated by Django 5.1.6 on 2025-03-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0004_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=40, verbose_name='Gender'),
        ),
    ]
