# Generated by Django 5.1.6 on 2025-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0006_alter_employee_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=40, verbose_name='Gender'),
        ),
    ]
