# Generated by Django 5.1.6 on 2025-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0010_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=40, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('Un Married', 'Un Married'), ('Married', 'Married')], default='Un Married', max_length=40, null=True, verbose_name='Maritial Status'),
        ),
    ]
