# Generated by Django 5.1.6 on 2025-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0011_alter_employee_gender_alter_employee_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Un Married', 'Un Married')], default='Un Married', max_length=40, null=True, verbose_name='Maritial Status'),
        ),
    ]
