# Generated by Django 5.1.6 on 2025-03-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0012_alter_employee_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='Designatory',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
