# Generated by Django 5.1.6 on 2025-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='online_payment_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
