# Generated by Django 5.1.6 on 2025-03-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_payment_method_alter_payment_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.service')),
            ],
        ),
    ]
