# Generated by Django 5.1.6 on 2025-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
    ]
