# Generated by Django 5.1.6 on 2025-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20),
        ),
    ]
